# Generated by Django 6.1.1 on 2026-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artclass',
            name='instructor',
            field=models.CharField(default='D-Art Studio Team', max_length=100),
        ),
    ]
